### ISSUE TITLE
Enhancement request: Sass/SCSS + Autoprefixer compilation

### ISSUE THREAD

**Issue by cmegown** [joezimjs/Webpack-Introduction-Tutorial#2]
The article was excellent, but I was hoping to find more information on handling CSS preprocessor compilation and bundling. I highly doubt I'm the only one who is going to feel the same way so I feel like this would be a great addition to this project.

I need to figure out this part sooner rather than later so I'll try to figure it out for myself. If I succeed I'll open up a pull request assuming nobody else has gotten around to it yet.

**Comment by joezimjs** [comment]
I wanted to do something like this but the article was already far longer than I wanted and I was just trying to teach the concepts. Hopefully you can figure it out, otherwise, I didn't teach the concepts well enough. Here's some hints.

You'll need the `sass-loader` and you need the `postcss-loader` with the `autoprefixer` plugin. For importing any kind of CSS, you'll also need to use the `css-loader` and `style-loader`. So the chain would be `style-loader`, then `css-loader`, then `postcss-loader` (with `autoprefixer` plugin specified in the options), then `sass-loader`.

If that's not enough to help you, let me know and I'll actually try to get it all set up for you and send you all the steps.
